version: '2'
services:  
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware
  
  jss:
    build: .
    volumes:
      - log-data:/Library/JSS/Logs
    ports:
      - "8444:8443"
      - "9080:8080"
    links:
      - mysql:db
    depends_on:
      - mysql
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03

  logshipper:
    image: logstash:2.3.4
    volumes:
      - "./etc/logstash.conf:/config-dir/logstash.conf"
    ports:
      - 5044
    command: "logstash -f /config-dir/logstash.conf"

  logreader:
    image: prima/filebeat:1.2.3
    links:
      - logshipper:logshipper
    volumes:
      - "./etc/filebeat.yml:/filebeat.yml"
      - log-data:/Library/JSS/Logs

      
volumes:
  db-data:
    driver: local
  log-data:
    driver: local

  
