version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  jss:
    build:
      context: .
      dockerfile: Dockerfile.tomcat80.jre8
    ports:
      - "8444:8443"
      - "9080:8080"
    links:
      - mysql:db
    depends_on:
      - mysql
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - SELF_SIGNED=0
      - PFX_CERT=/cert/server.pfx
      #- TLS_CERT=/cert/server.crt
      #- TLS_KEY=/cert/server.key
      #- CA_CERT=/cert/ca.crt
    volumes:
      - "./cert:/cert"

  samba:
    image: dperson/samba:latest
    ports:
      - "7139:139"
      - "7445:445"
    volumes:
      - "./distribution_point:/distribution_point"
    command:
      - "-u"
      - "jss;jss"
      - "-s"
      - "distribution_point;/distribution_point;yes;no;yes;all;jss"
      - "-p"
    environment:
      - TZ=UTC


volumes:
  db-data:
    driver: local
