version: '2'
services:  
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=jamfsoftware
      - MYSQL_PASSWORD=jamfsw03
      - MYSQL_DATABASE=jamfsoftware

  memcached:
    image: memcached

  jss:
    build: .
    volumes:
      - log-data:/Library/JSS/Logs
    ports:
      - "8444:8443"
      - "9080:8080"
    links:
      - mysql:db
      - memcached:memcached
      - logshipper:logshipper
    depends_on:
      - mysql
      - logshipper
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - JSS_CACHE_TYPE=memcached
      - JSS_MEMCACHED_SERVERS_0=memcached:11211
      - JSS_MEMCACHED_TTL=120
      - JSS_LOG4J_HOST=logshipper
      - JSS_LOG4J_PORT=4560

  cluster-jss:
    build: .
    volumes:
      - slave-log-data:/Library/JSS/Logs
    ports:
      - "8446:8443"
      - "9081:8080"
    links:
      - mysql:db
      - memcached:memcached
      - logshipper:logshipper
    depends_on:
      - mysql
      - logshipper
    environment:
      - JSS_DB_HOST=db
      - JSS_DB_PORT=3306
      - JSS_DB_NAME=jamfsoftware
      - JSS_DB_USERNAME=jamfsoftware
      - JSS_DB_PASSWORD=jamfsw03
      - JSS_CACHE_TYPE=memcached
      - JSS_MEMCACHED_SERVERS_0=memcached:11211
      - JSS_MEMCACHED_TTL=120
      - JSS_LOG4J_HOST=logshipper
      - JSS_LOG4J_PORT=4560



  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch


  logshipper:
    image: logstash:2.3.4
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    volumes:
      - "./etc/logstash.conf:/config-dir/logstash.conf"
    ports:
      - 5044
      - 4560
    command: "logstash -f /config-dir/logstash.conf"

  logreader:
    image: prima/filebeat:1.2.3
    depends_on:
      - jss
    links:
      - logshipper:logshipper
    volumes:
      - "./etc/filebeat.yml:/filebeat.yml"
      - log-data:/Library/JSS/Logs

  dash:
    image: bruienne/macdash:latest
    depends_on:
      - jss
    ports:
      - "8445:8000"
    links:
      - jss:jss
    environment:
      - JSS_URL=https://jss:8444
      - JSS_USER=admin
      - JSS_PASSWORD=password

      
volumes:
  db-data:
    driver: local
  log-data:
    driver: local
  slave-db-data:
    driver: local
  slave-log-data:
    driver: local


  
